package com.yopheu.games.aenean.config;

public enum GameState {
	PLAYERBETTING,
	DEALINITCARD,
	FIRSTCARDCHECK,
	INSURANCE,
	DEALERHASBLACKJACK,
	PLAYERHASBLACKJACK,
	PLAYERTURN,
	DEALERTURN,
	FINISH,
	READY;
}
